Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "10240"
    vb.cpus = "4"
  end

  config.vm.define "node1" do |node1|
    node1.vm.box = "bento/ubuntu-16.04"
  end

end