Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "1"
  end

  config.vm.define "node1" do |node1|
    node1.vm.box = "bento/ubuntu-16.04"
    node1.vm.network "public_network", bridge: "eno1"
  end

end